pr: none

jobs:
  - job: Default
    variables:
    - group: exoplanet-variables
    pool:
      vmImage: Ubuntu-16.04
    timeoutInMinutes: 120

    # steps:
    # - bash: .ci/azure/setup_conda.sh
    #   displayName: 'Setup conda'

    # - script: |
    #     source .ci/azure/activate_conda.sh
    #     env/bin/python -m pip install -U -r docs/requirements.txt
    #   displayName: 'Install dependencies'

    # - bash: .ci/azure/run_tutorials.sh
    #   displayName: 'Generate the tutorials'

    - bash: .ci/azure/build_docs.sh
      displayName: 'Build the docs'
      env:
        GITHUB_USER: $(GITHUB_USER)
        GITHUB_API_KEY: $(GITHUB_API_KEY)
        SOURCE_BRANCH: $(Build.SourceBranch)

    # - task: PublishPipelineArtifact@1
    #   inputs:
    #     path: $(Build.SourcesDirectory)/docs/notebooks
    #     artifact: Tutorials
    #   displayName: 'Upload the results'
    #   condition: always()
