pr: none
trigger:
- master
variables:
- group: exoplanet-variables
pool:
  vmImage: Ubuntu-16.04

steps:
- script: |
    git submodule update --init
  displayName: 'Fetch submodules'

- script: |
    source .ci/azure/setup_conda.sh
  displayName: 'Setup conda'

- script: |
    source .ci/azure/activate_conda.sh
    env/bin/python -m pip install -U -r paper/requirements.txt
    conda install -y -q -c conda-forge tectonic
  displayName: 'Install dependencies'

- script: |
    source .ci/azure/activate_conda.sh
    cd $(Build.SourcesDirectory)/paper/figures
    python run_notebooks.py
  displayName: 'Generate the figures'

- script: |
    source .ci/azure/activate_conda.sh
    cd $(Build.SourcesDirectory)/paper
    make
  displayName: 'Build the paper'
