name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: "py${{ matrix.python-version }} on ${{ matrix.os }} / pymc v${{ matrix.pymc-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8"]
        pymc-version: ["3.8", "3.9"]
        os: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v2
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      # Cache dependencies
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ matrix.os }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ matrix.os }}-pip-

      # Setup
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools numpy pybind11 wheel
          python -m pip install "pymc3==${{ matrix.pymc-version }}"
          python -m pip wheel --wheel-dir=~/.cache/pip/exoplanet --find-links=~/.cache/pip/exoplanet .[test]
          python -m pip install -U --find-links=~/.cache/pip/exoplanet -e .[test]
          python -c 'import theano; print(theano.config.__str__(print_doc=False))'

      - name: Run tests
        run: python -m pytest --cov=exoplanet -v tests

      # Uploading coverage report
      - name: Upload coverage
        if: success()
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          if [ -z "$COVERALLS_REPO_TOKEN" ]; then
            echo "Skipping on pull requests"
          else
            coveralls
          fi
